import type { Metadata } from "next";
import { Geist, Geist_Mono,Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import ThemeProvider from "./components/ThemeProvider";
import NavBar from "./components/NavBar";

const notoThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["latin","thai"],
  weight:["400","500","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoThai.className} antialiased bg-white dark:bg-[#1A1818]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar></NavBar>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
